spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: youtube-clone-db
  server:
    port: 8099
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://youtube-clone-test-auth.eu.auth0.com/
      okta:
        oauth2:
          issuer: https://youtube-clone-test-auth.eu.auth0.com/
          audience: http://localhost:8080

  cloud:
    aws:
      region:
        static: eu-west-2
      stack:
        auto: false

  logging:
    level:
      com.auth0.example: INFO
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
      org.springframework.boot: DEBUG

  auth0:
    userinfoEndpoint: https://youtube-clone-test-auth.eu.auth0.com/userinfo

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
    tags-sorter: alpha